export const PERMISSIONS = {
  ORGANIZATION_READ: 'organization.read',
  ORGANIZATION_EDIT: 'organization.edit',
  LOCATION_READ: 'location.read',
  LOCATION_EDIT: 'location.edit',
  MEMBERSHIPS_READ: 'memberships.read',
  INVITATIONS_CREATE: 'invitations.create',
  INVITATIONS_REVOKE: 'invitations.revoke',
  MEMBERSHIPS_STATUS: 'memberships.status',
  MEMBERSHIPS_ROLES: 'memberships.roles',
  MEMBERSHIPS_LOCATION_ACCESS: 'memberships.location_access',
  ROLES_READ: 'roles.read',
  AUDIT_READ: 'audit.read',
  ARTISTS_READ: 'artists.read',
  ARTISTS_WRITE: 'artists.write',
  ARTISTS_ARCHIVE: 'artists.archive',
  CONTACTS_READ: 'contacts.read',
  CONTACTS_WRITE: 'contacts.write',
  CONTACTS_ARCHIVE: 'contacts.archive',
  BUSINESS_PARTNERS_READ: 'business_partners.read',
  BUSINESS_PARTNERS_WRITE: 'business_partners.write',
  BUSINESS_PARTNERS_ARCHIVE: 'business_partners.archive',
  EVENT_FORMATS_READ: 'event_formats.read',
  EVENT_FORMATS_WRITE: 'event_formats.write',
  EVENT_FORMATS_ARCHIVE: 'event_formats.archive',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_CATALOG: ReadonlyArray<{
  key: PermissionKey;
  description: string;
}> = [
  { key: PERMISSIONS.ORGANIZATION_READ, description: 'Organisation ansehen' },
  { key: PERMISSIONS.ORGANIZATION_EDIT, description: 'Organisation bearbeiten' },
  { key: PERMISSIONS.LOCATION_READ, description: 'Location ansehen' },
  { key: PERMISSIONS.LOCATION_EDIT, description: 'Location bearbeiten' },
  { key: PERMISSIONS.MEMBERSHIPS_READ, description: 'Mitgliedschaften ansehen' },
  { key: PERMISSIONS.INVITATIONS_CREATE, description: 'Benutzer einladen' },
  { key: PERMISSIONS.INVITATIONS_REVOKE, description: 'Einladungen widerrufen' },
  {
    key: PERMISSIONS.MEMBERSHIPS_STATUS,
    description: 'Mitgliedschaften sperren oder reaktivieren',
  },
  { key: PERMISSIONS.MEMBERSHIPS_ROLES, description: 'Rollen zuweisen' },
  {
    key: PERMISSIONS.MEMBERSHIPS_LOCATION_ACCESS,
    description: 'Location-Zugriff verwalten',
  },
  { key: PERMISSIONS.ROLES_READ, description: 'Rollen ansehen' },
  { key: PERMISSIONS.AUDIT_READ, description: 'Audit-Protokoll ansehen' },
  { key: PERMISSIONS.ARTISTS_READ, description: 'Artists ansehen' },
  { key: PERMISSIONS.ARTISTS_WRITE, description: 'Artists anlegen und bearbeiten' },
  { key: PERMISSIONS.ARTISTS_ARCHIVE, description: 'Artists archivieren und reaktivieren' },
  { key: PERMISSIONS.CONTACTS_READ, description: 'Kontakte ansehen' },
  { key: PERMISSIONS.CONTACTS_WRITE, description: 'Kontakte anlegen und bearbeiten' },
  { key: PERMISSIONS.CONTACTS_ARCHIVE, description: 'Kontakte archivieren und reaktivieren' },
  {
    key: PERMISSIONS.BUSINESS_PARTNERS_READ,
    description: 'Geschäftspartner ansehen',
  },
  {
    key: PERMISSIONS.BUSINESS_PARTNERS_WRITE,
    description: 'Geschäftspartner anlegen und bearbeiten',
  },
  {
    key: PERMISSIONS.BUSINESS_PARTNERS_ARCHIVE,
    description: 'Geschäftspartner archivieren und reaktivieren',
  },
  { key: PERMISSIONS.EVENT_FORMATS_READ, description: 'Veranstaltungsformate ansehen' },
  {
    key: PERMISSIONS.EVENT_FORMATS_WRITE,
    description: 'Veranstaltungsformate anlegen und bearbeiten',
  },
  {
    key: PERMISSIONS.EVENT_FORMATS_ARCHIVE,
    description: 'Veranstaltungsformate archivieren und reaktivieren',
  },
];

export const STANDARD_ROLES = [
  { key: 'administrator', name: 'Administrator', allPermissions: true, permissionKeys: [] },
  {
    key: 'management_finance',
    name: 'Management & Finanzen',
    allPermissions: false,
    permissionKeys: [
      PERMISSIONS.ORGANIZATION_READ,
      PERMISSIONS.LOCATION_READ,
      PERMISSIONS.ARTISTS_READ,
      PERMISSIONS.CONTACTS_READ,
      PERMISSIONS.CONTACTS_WRITE,
      PERMISSIONS.CONTACTS_ARCHIVE,
      PERMISSIONS.BUSINESS_PARTNERS_READ,
      PERMISSIONS.BUSINESS_PARTNERS_WRITE,
      PERMISSIONS.BUSINESS_PARTNERS_ARCHIVE,
      PERMISSIONS.EVENT_FORMATS_READ,
      PERMISSIONS.EVENT_FORMATS_WRITE,
      PERMISSIONS.EVENT_FORMATS_ARCHIVE,
    ],
  },
  {
    key: 'booking',
    name: 'Booking',
    allPermissions: false,
    permissionKeys: [
      PERMISSIONS.ORGANIZATION_READ,
      PERMISSIONS.LOCATION_READ,
      PERMISSIONS.ARTISTS_READ,
      PERMISSIONS.ARTISTS_WRITE,
      PERMISSIONS.ARTISTS_ARCHIVE,
      PERMISSIONS.CONTACTS_READ,
      PERMISSIONS.CONTACTS_WRITE,
      PERMISSIONS.CONTACTS_ARCHIVE,
      PERMISSIONS.BUSINESS_PARTNERS_READ,
      PERMISSIONS.EVENT_FORMATS_READ,
    ],
  },
  {
    key: 'production',
    name: 'Produktion',
    allPermissions: false,
    permissionKeys: [
      PERMISSIONS.ORGANIZATION_READ,
      PERMISSIONS.LOCATION_READ,
      PERMISSIONS.ARTISTS_READ,
      PERMISSIONS.CONTACTS_READ,
      PERMISSIONS.BUSINESS_PARTNERS_READ,
      PERMISSIONS.EVENT_FORMATS_READ,
      PERMISSIONS.EVENT_FORMATS_WRITE,
    ],
  },
  {
    key: 'read_only',
    name: 'Lesend',
    allPermissions: false,
    permissionKeys: [
      PERMISSIONS.ORGANIZATION_READ,
      PERMISSIONS.LOCATION_READ,
      PERMISSIONS.ARTISTS_READ,
      PERMISSIONS.CONTACTS_READ,
      PERMISSIONS.BUSINESS_PARTNERS_READ,
      PERMISSIONS.EVENT_FORMATS_READ,
    ],
  },
] as const;
