export const PERMISSIONS = {
  ORGANIZATION_READ: 'organization.read',
  ORGANIZATION_EDIT: 'organization.edit',
  LOCATION_READ: 'location.read',
  LOCATION_EDIT: 'location.edit',
  MEMBERSHIPS_READ: 'memberships.read',
  INVITATIONS_CREATE: 'invitations.create',
  INVITATIONS_REVOKE: 'invitations.revoke',
  MEMBERSHIPS_STATUS: 'memberships.status',
  MEMBERSHIPS_ROLES: 'memberships.roles',
  MEMBERSHIPS_LOCATION_ACCESS: 'memberships.location_access',
  ROLES_READ: 'roles.read',
  AUDIT_READ: 'audit.read',
  ARTISTS_READ: 'artists.read',
  ARTISTS_WRITE: 'artists.write',
  ARTISTS_ARCHIVE: 'artists.archive',
  CONTACTS_READ: 'contacts.read',
  CONTACTS_WRITE: 'contacts.write',
  CONTACTS_ARCHIVE: 'contacts.archive',
  BUSINESS_PARTNERS_READ: 'business_partners.read',
  BUSINESS_PARTNERS_WRITE: 'business_partners.write',
  BUSINESS_PARTNERS_ARCHIVE: 'business_partners.archive',
  EVENT_FORMATS_READ: 'event_formats.read',
  EVENT_FORMATS_WRITE: 'event_formats.write',
  EVENT_FORMATS_ARCHIVE: 'event_formats.archive',
  EVENTS_READ: 'events.read',
  EVENTS_WRITE: 'events.write',
  EVENTS_STATUS: 'events.status',
  DATE_OPTIONS_READ: 'date_options.read',
  DATE_OPTIONS_WRITE: 'date_options.write',
  DATE_OPTIONS_CONVERT: 'date_options.convert',
  BOOKINGS_READ: 'bookings.read',
  BOOKINGS_WRITE: 'bookings.write',
  BOOKINGS_STATUS: 'bookings.status',
  BOOKINGS_FINANCE: 'bookings.finance',
  LINEUP_WRITE: 'lineup.write',
  SERVICES_READ: 'services.read',
  SERVICES_WRITE: 'services.write',
  SERVICES_ARCHIVE: 'services.archive',
  CALCULATIONS_READ: 'calculations.read',
  CALCULATIONS_WRITE: 'calculations.write',
  CALCULATIONS_PURCHASE: 'calculations.purchase',
  CALCULATIONS_SALES: 'calculations.sales',
  CALCULATIONS_APPROVE: 'calculations.approve',
  REVENUE_TEMPLATES_READ: 'revenue_templates.read',
  REVENUE_TEMPLATES_WRITE: 'revenue_templates.write',
  REVENUE_TEMPLATES_ARCHIVE: 'revenue_templates.archive',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_CATALOG: ReadonlyArray<{
  key: PermissionKey;
  description: string;
}> = [
  { key: PERMISSIONS.ORGANIZATION_READ, description: 'Organisation ansehen' },
  { key: PERMISSIONS.ORGANIZATION_EDIT, description: 'Organisation bearbeiten' },
  { key: PERMISSIONS.LOCATION_READ, description: 'Location ansehen' },
  { key: PERMISSIONS.LOCATION_EDIT, description: 'Location bearbeiten' },
  { key: PERMISSIONS.MEMBERSHIPS_READ, description: 'Mitgliedschaften ansehen' },
  { key: PERMISSIONS.INVITATIONS_CREATE, description: 'Benutzer einladen' },
  { key: PERMISSIONS.INVITATIONS_REVOKE, description: 'Einladungen widerrufen' },
  {
    key: PERMISSIONS.MEMBERSHIPS_STATUS,
    description: 'Mitgliedschaften sperren oder reaktivieren',
  },
  { key: PERMISSIONS.MEMBERSHIPS_ROLES, description: 'Rollen zuweisen' },
  {
    key: PERMISSIONS.MEMBERSHIPS_LOCATION_ACCESS,
    description: 'Location-Zugriff verwalten',
  },
  { key: PERMISSIONS.ROLES_READ, description: 'Rollen ansehen' },
  { key: PERMISSIONS.AUDIT_READ, description: 'Audit-Protokoll ansehen' },
  { key: PERMISSIONS.ARTISTS_READ, description: 'Artists ansehen' },
  { key: PERMISSIONS.ARTISTS_WRITE, description: 'Artists anlegen und bearbeiten' },
  { key: PERMISSIONS.ARTISTS_ARCHIVE, description: 'Artists archivieren und reaktivieren' },
  { key: PERMISSIONS.CONTACTS_READ, description: 'Kontakte ansehen' },
  { key: PERMISSIONS.CONTACTS_WRITE, description: 'Kontakte anlegen und bearbeiten' },
  { key: PERMISSIONS.CONTACTS_ARCHIVE, description: 'Kontakte archivieren und reaktivieren' },
  {
    key: PERMISSIONS.BUSINESS_PARTNERS_READ,
    description: 'Geschäftspartner ansehen',
  },
  {
    key: PERMISSIONS.BUSINESS_PARTNERS_WRITE,
    description: 'Geschäftspartner anlegen und bearbeiten',
  },
  {
    key: PERMISSIONS.BUSINESS_PARTNERS_ARCHIVE,
    description: 'Geschäftspartner archivieren und reaktivieren',
  },
  { key: PERMISSIONS.EVENT_FORMATS_READ, description: 'Veranstaltungsformate ansehen' },
  {
    key: PERMISSIONS.EVENT_FORMATS_WRITE,
    description: 'Veranstaltungsformate anlegen und bearbeiten',
  },
  {
    key: PERMISSIONS.EVENT_FORMATS_ARCHIVE,
    description: 'Veranstaltungsformate archivieren und reaktivieren',
  },
  { key: PERMISSIONS.EVENTS_READ, description: 'Veranstaltungen ansehen' },
  { key: PERMISSIONS.EVENTS_WRITE, description: 'Veranstaltungen anlegen und bearbeiten' },
  { key: PERMISSIONS.EVENTS_STATUS, description: 'Veranstaltungsstatus ändern' },
  { key: PERMISSIONS.DATE_OPTIONS_READ, description: 'Terminoptionen und Freitermine ansehen' },
  { key: PERMISSIONS.DATE_OPTIONS_WRITE, description: 'Terminoptionen anlegen und bearbeiten' },
  {
    key: PERMISSIONS.DATE_OPTIONS_CONVERT,
    description: 'Terminoptionen in Veranstaltungen umwandeln',
  },
  { key: PERMISSIONS.BOOKINGS_READ, description: 'Booking- und Line-up-Grunddaten ansehen' },
  { key: PERMISSIONS.BOOKINGS_WRITE, description: 'Bookings anlegen und bearbeiten' },
  { key: PERMISSIONS.BOOKINGS_STATUS, description: 'Bookingstatus ändern' },
  {
    key: PERMISSIONS.BOOKINGS_FINANCE,
    description: 'Booking-Gagen und Reisekosten ansehen und bearbeiten',
  },
  { key: PERMISSIONS.LINEUP_WRITE, description: 'Line-up-Vorgaben und Reihenfolge bearbeiten' },
  {
    key: PERMISSIONS.SERVICES_READ,
    description: 'Leistungskategorien und Leistungskatalog ansehen',
  },
  { key: PERMISSIONS.SERVICES_WRITE, description: 'Leistungen und Dienstleisterpreise bearbeiten' },
  { key: PERMISSIONS.SERVICES_ARCHIVE, description: 'Leistungsdaten archivieren und reaktivieren' },
  { key: PERMISSIONS.CALCULATIONS_READ, description: 'Kalkulationsstruktur ansehen' },
  {
    key: PERMISSIONS.CALCULATIONS_WRITE,
    description: 'Veranstaltungspositionen und Kalkulationen bearbeiten',
  },
  {
    key: PERMISSIONS.CALCULATIONS_PURCHASE,
    description: 'Einkaufspreise und Kosten ansehen und bearbeiten',
  },
  {
    key: PERMISSIONS.CALCULATIONS_SALES,
    description: 'Verkaufspreise und Marge ansehen und bearbeiten',
  },
  { key: PERMISSIONS.CALCULATIONS_APPROVE, description: 'Kalkulationen freigeben' },
  { key: PERMISSIONS.REVENUE_TEMPLATES_READ, description: 'Erlös- und Steuervorlagen ansehen' },
  {
    key: PERMISSIONS.REVENUE_TEMPLATES_WRITE,
    description: 'Erlös- und Steuervorlagen anlegen und bearbeiten',
  },
  {
    key: PERMISSIONS.REVENUE_TEMPLATES_ARCHIVE,
    description: 'Erlös- und Steuervorlagen archivieren und reaktivieren',
  },
];

export const STANDARD_ROLES = [
  { key: 'administrator', name: 'Administrator', allPermissions: true, permissionKeys: [] },
  {
    key: 'management_finance',
    name: 'Management & Finanzen',
    allPermissions: false,
    permissionKeys: [
      PERMISSIONS.ORGANIZATION_READ,
      PERMISSIONS.LOCATION_READ,
      PERMISSIONS.ARTISTS_READ,
      PERMISSIONS.CONTACTS_READ,
      PERMISSIONS.CONTACTS_WRITE,
      PERMISSIONS.CONTACTS_ARCHIVE,
      PERMISSIONS.BUSINESS_PARTNERS_READ,
      PERMISSIONS.BUSINESS_PARTNERS_WRITE,
      PERMISSIONS.BUSINESS_PARTNERS_ARCHIVE,
      PERMISSIONS.EVENT_FORMATS_READ,
      PERMISSIONS.EVENT_FORMATS_WRITE,
      PERMISSIONS.EVENT_FORMATS_ARCHIVE,
      PERMISSIONS.EVENTS_READ,
      PERMISSIONS.EVENTS_WRITE,
      PERMISSIONS.EVENTS_STATUS,
      PERMISSIONS.DATE_OPTIONS_READ,
      PERMISSIONS.DATE_OPTIONS_WRITE,
      PERMISSIONS.DATE_OPTIONS_CONVERT,
      PERMISSIONS.BOOKINGS_READ,
      PERMISSIONS.BOOKINGS_WRITE,
      PERMISSIONS.BOOKINGS_STATUS,
      PERMISSIONS.BOOKINGS_FINANCE,
      PERMISSIONS.LINEUP_WRITE,
      PERMISSIONS.SERVICES_READ,
      PERMISSIONS.SERVICES_WRITE,
      PERMISSIONS.SERVICES_ARCHIVE,
      PERMISSIONS.CALCULATIONS_READ,
      PERMISSIONS.CALCULATIONS_WRITE,
      PERMISSIONS.CALCULATIONS_PURCHASE,
      PERMISSIONS.CALCULATIONS_SALES,
      PERMISSIONS.CALCULATIONS_APPROVE,
      PERMISSIONS.REVENUE_TEMPLATES_READ,
      PERMISSIONS.REVENUE_TEMPLATES_WRITE,
      PERMISSIONS.REVENUE_TEMPLATES_ARCHIVE,
    ],
  },
  {
    key: 'booking',
    name: 'Booking',
    allPermissions: false,
    permissionKeys: [
      PERMISSIONS.ORGANIZATION_READ,
      PERMISSIONS.LOCATION_READ,
      PERMISSIONS.ARTISTS_READ,
      PERMISSIONS.ARTISTS_WRITE,
      PERMISSIONS.ARTISTS_ARCHIVE,
      PERMISSIONS.CONTACTS_READ,
      PERMISSIONS.CONTACTS_WRITE,
      PERMISSIONS.CONTACTS_ARCHIVE,
      PERMISSIONS.BUSINESS_PARTNERS_READ,
      PERMISSIONS.EVENT_FORMATS_READ,
      PERMISSIONS.EVENTS_READ,
      PERMISSIONS.EVENTS_WRITE,
      PERMISSIONS.EVENTS_STATUS,
      PERMISSIONS.DATE_OPTIONS_READ,
      PERMISSIONS.DATE_OPTIONS_WRITE,
      PERMISSIONS.DATE_OPTIONS_CONVERT,
      PERMISSIONS.BOOKINGS_READ,
      PERMISSIONS.BOOKINGS_WRITE,
      PERMISSIONS.BOOKINGS_STATUS,
      PERMISSIONS.BOOKINGS_FINANCE,
      PERMISSIONS.LINEUP_WRITE,
      PERMISSIONS.SERVICES_READ,
    ],
  },
  {
    key: 'production',
    name: 'Produktion',
    allPermissions: false,
    permissionKeys: [
      PERMISSIONS.ORGANIZATION_READ,
      PERMISSIONS.LOCATION_READ,
      PERMISSIONS.ARTISTS_READ,
      PERMISSIONS.CONTACTS_READ,
      PERMISSIONS.BUSINESS_PARTNERS_READ,
      PERMISSIONS.EVENT_FORMATS_READ,
      PERMISSIONS.EVENT_FORMATS_WRITE,
      PERMISSIONS.EVENTS_READ,
      PERMISSIONS.EVENTS_WRITE,
      PERMISSIONS.DATE_OPTIONS_READ,
      PERMISSIONS.BOOKINGS_READ,
      PERMISSIONS.SERVICES_READ,
      PERMISSIONS.CALCULATIONS_READ,
    ],
  },
  {
    key: 'read_only',
    name: 'Lesend',
    allPermissions: false,
    permissionKeys: [
      PERMISSIONS.ORGANIZATION_READ,
      PERMISSIONS.LOCATION_READ,
      PERMISSIONS.ARTISTS_READ,
      PERMISSIONS.CONTACTS_READ,
      PERMISSIONS.BUSINESS_PARTNERS_READ,
      PERMISSIONS.EVENT_FORMATS_READ,
      PERMISSIONS.EVENTS_READ,
      PERMISSIONS.DATE_OPTIONS_READ,
      PERMISSIONS.BOOKINGS_READ,
      PERMISSIONS.SERVICES_READ,
      PERMISSIONS.CALCULATIONS_READ,
    ],
  },
] as const;
